apiVersion: v1
kind: Secret
metadata:
    name: node-red-secret
stringData:
    NODE_RED_CREDENTIAL_SECRET: ENC[AES256_GCM,data:+ysJ0bKwLC94tQ5rn5kQYfVrBYKSw0dP60UlDzej6tx2L/PrJKWzqW3Jv6dvrvxxPwUzQSBy2v/YrYKkhsIJqA==,iv:JHPZlGAN+4e4ahOws4w3Mod6t/oQN6GlinCFBiV8xnY=,tag:FJYZdVLjDi8qQzBFNQfGtg==,type:str]
sops:
    age:
        - recipient: age1yefuafglgmxqztx50yt6ts2a2z9tg48ywnhgrz4zxlqh5w6xvqqqr22agq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMlVLcEhkQ0JjRHBTSkR4
            L2hXdksrZjdMYlQzeWxrdlJBRitQVDlDV0E0CkJPcm5INkhMWDJBbUhrS3VSc0ZK
            Z3ZPa2tVaTNIUnVWTVhXY01CMGNaelUKLS0tIDVtaFg4d0gxanZDNk55a2FxaXFh
            M3ZVWkxmZlR5ZkNyOW9ic0V5cnNzemcKezJklUzoH1kIJl1UHaYQUMQ3Hh1Ui344
            ekEi5QBx8Te35nAcl/0LcknWm1rr+8h6hQh1lt4TYjYYqEoD/PkXgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T05:21:46Z"
    mac: ENC[AES256_GCM,data:hm+EBOwguq/cuCQrDi9ci7ojbfVwWmP+XxM88gJAtFcgxTMnU1naMKkKglrl0+bY2eoX6wWzFsLs6w/qFKeuBreP+yrNmQzuDi0LI853DympAVnjf8hEBCaRjm7hj9uSSgHhAMTVeevghzm/sxY2MjrKp91URTnISK/xyWs2g7I=,iv:jIifanN/7ob6S7SlI1haeb2h6P/PuBUW9Zip8cZVLGM=,tag:LNFwsEDosWH7ituJR7vOqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
