[env]
_.file = '.env'
_.python.venv = ".venv"

[tools]
"node" = "24"
"aqua:cilium/cilium-cli" = "0.18.9"
"aqua:cli/cli" = "2.83.2"
"aqua:cloudflare/cloudflared" = "2025.11.1"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:getsops/sops" = "3.11.0"
"aqua:go-task/task" = "3.46.3"
"aqua:helm/helm" = "4.0.4"
"aqua:helmfile/helmfile" = "1.2.3"
"aqua:jqlang/jq" = "1.8.1"
"aqua:kubernetes-sigs/kustomize" = "5.7.1"
"aqua:kubernetes/kubernetes/kubectl" = "1.35.0"
"aqua:mikefarah/yq" = "4.50.1"
"aqua:yannh/kubeconform" = "0.7.0"
"stern" = "latest"
"k9s" = "latest"
