apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
stringData:
    #ENC[AES256_GCM,data:zbPRaW4btkxHpyX1ovK9yiwhGy8Nz0c=,iv:9cXP0TJxGamVLwqbvUD9knW4xYc/tiKinTV99CCcF84=,tag:NSkH3KP1b//j4atgC9NY4g==,type:comment]
    #ENC[AES256_GCM,data:QQGamiV3afqmiQwa/ShK,iv:DvB052dzk4cwzvMoerg0BZAUxhbZyAY+l/0z6HGl/zw=,tag:JDujf7CTqCfBGmh8yK0dqg==,type:comment]
    HASS_OIDC_CLIENT_ID: ENC[AES256_GCM,data:fdBnPkgdOzGr80HxMuG/gi0jHeb/x5AbMk4YvnrXj1PqZyqyVulSGA==,iv:FnykZIP6sufwVfDxHotGnQWa6Nf9/rgmdyRvK8J0QuM=,tag:AWXcSuXi1lY9SDxnGTJCAQ==,type:str]
    HASS_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:WJcVcYuuyGljl76sjVK8hNVKT1IkT6iDfX1VRPh49GD/GUnfESU9QI6ohfS4L1z8Z17LScrGm8+G1k8XDj+5nWT6SrcGoCBNdAs6ZQ8i8K1+c5psAC3W6gg8IY3uxMZqayP2dJFxAucfFzjk5elUxehCDiANz22dTvS+NFEufLQ=,iv:RzP07Ee8sMiTS6Npd03ry+Rh8tS5TFyso5G9IPkAtWQ=,tag:N6XJpAL9Mv62PPnk+ma4RQ==,type:str]
sops:
    age:
        - recipient: age1yefuafglgmxqztx50yt6ts2a2z9tg48ywnhgrz4zxlqh5w6xvqqqr22agq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MlZhSlczbmJWczJZdVg1
            TkhVQVZYVFdXQmVoUmE5Znh5NzhKcm13YUVJCktTOENmY05ENVRtWjdNcVFvMWRR
            UFg4c3M4SXhjU2ZWQ2xVNVcvUmdBUVEKLS0tIG9tYlJ0U0NLU3VQUlJ4YlUvMHZw
            WU1IZkV3ajRyK25DbFo4VWVRWld3clEKWWUH7t8AgLMfAz2db0/5hEJcnhwZtFPc
            6/6+Ra2vaIrjyh45UEqc6LAQAvqW/PDVxKI5sj9SrncyBL50f4S9ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T23:35:52Z"
    mac: ENC[AES256_GCM,data:GkemyAasg0nBBkxs6xBsXp+3uVeVNJRNP4j4iA0GQAbhOmToccCwT3aTyT1gLlfWDjX4QFmXAkoWl9xoJWOxmHOW0gWzT0IKUHj+PGaKPjkiakax99Y3pd6fenDbMZuEdf36V2+y9rbs3xSXS66CdGuhY+lPyI6T3wdqMkTMXgU=,iv:+5NYJYAGe8pPQ8kwI9BrzjfRR5tjHGNkHCST4Uvyt40=,tag:QiobB/vBI15J/X2ysniv1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-pg-r2
stringData:
    R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:SuTmcyY47Fpz1SseCRStnG1LRYVPm9xyl9Di39m4+qo=,iv:t+7BKY3oHsHwYvWWqVXivpCYlXCv3+vHDQKUFxxlHo4=,tag:dTRidzzi/KPvnBvWYqMF3A==,type:str]
    R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:X31gUsg1GyI/KtRlrBYM1Msanpz601a1LkU/Nu3DWa0s7JYksvS/qu/8pKz502ekyUnuMDQdquPx4w0cTGlkbg==,iv:aLXzOHf3XgREmSZJ1phl2jSDsDEZ2DXTtQFcF9Gg9j8=,tag:vEZOYFnBANzo17MVbTptDA==,type:str]
sops:
    age:
        - recipient: age1yefuafglgmxqztx50yt6ts2a2z9tg48ywnhgrz4zxlqh5w6xvqqqr22agq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MlZhSlczbmJWczJZdVg1
            TkhVQVZYVFdXQmVoUmE5Znh5NzhKcm13YUVJCktTOENmY05ENVRtWjdNcVFvMWRR
            UFg4c3M4SXhjU2ZWQ2xVNVcvUmdBUVEKLS0tIG9tYlJ0U0NLU3VQUlJ4YlUvMHZw
            WU1IZkV3ajRyK25DbFo4VWVRWld3clEKWWUH7t8AgLMfAz2db0/5hEJcnhwZtFPc
            6/6+Ra2vaIrjyh45UEqc6LAQAvqW/PDVxKI5sj9SrncyBL50f4S9ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T23:35:52Z"
    mac: ENC[AES256_GCM,data:GkemyAasg0nBBkxs6xBsXp+3uVeVNJRNP4j4iA0GQAbhOmToccCwT3aTyT1gLlfWDjX4QFmXAkoWl9xoJWOxmHOW0gWzT0IKUHj+PGaKPjkiakax99Y3pd6fenDbMZuEdf36V2+y9rbs3xSXS66CdGuhY+lPyI6T3wdqMkTMXgU=,iv:+5NYJYAGe8pPQ8kwI9BrzjfRR5tjHGNkHCST4Uvyt40=,tag:QiobB/vBI15J/X2ysniv1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
