apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
stringData:
    #ENC[AES256_GCM,data:zbPRaW4btkxHpyX1ovK9yiwhGy8Nz0c=,iv:9cXP0TJxGamVLwqbvUD9knW4xYc/tiKinTV99CCcF84=,tag:NSkH3KP1b//j4atgC9NY4g==,type:comment]
    HASS_LATITUDE: ENC[AES256_GCM,data:PQtt3HgHkFY=,iv:MybKdvk237MpMVVBsTtnYz8phSOYRDrUJ7OEGzht0f8=,tag:NrJqnTjaajOrV0x+kJ6u4g==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:HjaPVmWAgxeDYw==,iv:t0JF0p4YZCIEPOZS+FHJa0Tt69Li/LzTYo5ePdBwrMw=,tag:VGjvIIWcqhTdQiDzov0UPw==,type:str]
    #ENC[AES256_GCM,data:9oBXDFag+QuGbEa5UZVrsw==,iv:L0fPv3y7AwZ0GYeZeiw4X5e8OaQNGccZ+J5Xji1+3rA=,tag:T3+A1ivWYpcj13ru7YWdcw==,type:comment]
    #ENC[AES256_GCM,data:QQGamiV3afqmiQwa/ShK,iv:DvB052dzk4cwzvMoerg0BZAUxhbZyAY+l/0z6HGl/zw=,tag:JDujf7CTqCfBGmh8yK0dqg==,type:comment]
    HASS_OIDC_CLIENT_ID: ENC[AES256_GCM,data:fdBnPkgdOzGr80HxMuG/gi0jHeb/x5AbMk4YvnrXj1PqZyqyVulSGA==,iv:FnykZIP6sufwVfDxHotGnQWa6Nf9/rgmdyRvK8J0QuM=,tag:AWXcSuXi1lY9SDxnGTJCAQ==,type:str]
    HASS_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:WJcVcYuuyGljl76sjVK8hNVKT1IkT6iDfX1VRPh49GD/GUnfESU9QI6ohfS4L1z8Z17LScrGm8+G1k8XDj+5nWT6SrcGoCBNdAs6ZQ8i8K1+c5psAC3W6gg8IY3uxMZqayP2dJFxAucfFzjk5elUxehCDiANz22dTvS+NFEufLQ=,iv:RzP07Ee8sMiTS6Npd03ry+Rh8tS5TFyso5G9IPkAtWQ=,tag:N6XJpAL9Mv62PPnk+ma4RQ==,type:str]
sops:
    age:
        - recipient: age1yefuafglgmxqztx50yt6ts2a2z9tg48ywnhgrz4zxlqh5w6xvqqqr22agq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MlZhSlczbmJWczJZdVg1
            TkhVQVZYVFdXQmVoUmE5Znh5NzhKcm13YUVJCktTOENmY05ENVRtWjdNcVFvMWRR
            UFg4c3M4SXhjU2ZWQ2xVNVcvUmdBUVEKLS0tIG9tYlJ0U0NLU3VQUlJ4YlUvMHZw
            WU1IZkV3ajRyK25DbFo4VWVRWld3clEKWWUH7t8AgLMfAz2db0/5hEJcnhwZtFPc
            6/6+Ra2vaIrjyh45UEqc6LAQAvqW/PDVxKI5sj9SrncyBL50f4S9ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T00:32:50Z"
    mac: ENC[AES256_GCM,data:xYLdrUihwP3Gq0N/d++TD8bCsIhcWBdrszb0Bk7bZuT4JJSum/U+9oI3uC8+pf55QPjkdQCuyzz6/SO+rsEKP5Olw00Le7nN9kmxMukiBYiJxSQq6yRU4Qwoq+6NwV8+eB4ALZOl1hwBZKv9NA/0DpjInAcAE3+7uUjXZoEPLyA=,iv:18PhJZ8h+uJtPAEL9MEHevC0R3oEvkk1LdIymxPtklQ=,tag:8L4fcbusWrlgyCY6u6uQnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-pg-r2
stringData:
    R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:SuTmcyY47Fpz1SseCRStnG1LRYVPm9xyl9Di39m4+qo=,iv:t+7BKY3oHsHwYvWWqVXivpCYlXCv3+vHDQKUFxxlHo4=,tag:dTRidzzi/KPvnBvWYqMF3A==,type:str]
    R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:X31gUsg1GyI/KtRlrBYM1Msanpz601a1LkU/Nu3DWa0s7JYksvS/qu/8pKz502ekyUnuMDQdquPx4w0cTGlkbg==,iv:aLXzOHf3XgREmSZJ1phl2jSDsDEZ2DXTtQFcF9Gg9j8=,tag:vEZOYFnBANzo17MVbTptDA==,type:str]
sops:
    age:
        - recipient: age1yefuafglgmxqztx50yt6ts2a2z9tg48ywnhgrz4zxlqh5w6xvqqqr22agq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MlZhSlczbmJWczJZdVg1
            TkhVQVZYVFdXQmVoUmE5Znh5NzhKcm13YUVJCktTOENmY05ENVRtWjdNcVFvMWRR
            UFg4c3M4SXhjU2ZWQ2xVNVcvUmdBUVEKLS0tIG9tYlJ0U0NLU3VQUlJ4YlUvMHZw
            WU1IZkV3ajRyK25DbFo4VWVRWld3clEKWWUH7t8AgLMfAz2db0/5hEJcnhwZtFPc
            6/6+Ra2vaIrjyh45UEqc6LAQAvqW/PDVxKI5sj9SrncyBL50f4S9ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T00:32:50Z"
    mac: ENC[AES256_GCM,data:xYLdrUihwP3Gq0N/d++TD8bCsIhcWBdrszb0Bk7bZuT4JJSum/U+9oI3uC8+pf55QPjkdQCuyzz6/SO+rsEKP5Olw00Le7nN9kmxMukiBYiJxSQq6yRU4Qwoq+6NwV8+eB4ALZOl1hwBZKv9NA/0DpjInAcAE3+7uUjXZoEPLyA=,iv:18PhJZ8h+uJtPAEL9MEHevC0R3oEvkk1LdIymxPtklQ=,tag:8L4fcbusWrlgyCY6u6uQnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
