---
# IoT Network - for Home Assistant, ESPHome, etc.
# Since the cluster is already on the IoT VLAN, no VLAN tagging is needed.
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: iot
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "iot",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "static"
      }
    }
