---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-tailscale
  namespace: storage
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: longhorn-ui
      port:
        name: longhorn-ui
  tls:
    - hosts:
        - longhorn